[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
sea-orm = { workspace = true }

poem = {workspace = true}
poem-openapi = { workspace = true}
